name: Publish

on:
  push:
    branches: [master]

jobs:
  test-and-distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Assemble Release Bundle
        run:
          ./gradlew bundleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
            releaseDirectory: app/build/outputs/bundle/release
            signingKeyBase64: ${{ secrets.KEYSTORE }}
            alias: ${{ secrets.KEY_ALIAS }}
            keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
            keyPassword: ${{ secrets.EY_PASSWORD }}
