name: Publish

on:
  push:
    branches: [master]

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run micro tests
        run: ./gradlew clean testDebug

  android_tests:
    runs-on: [ macos-latest ]
    steps:
        - uses: actions/checkout@v3

        - name: Instrumentation Tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 30
            target: google_apis
            arch: x86_64
            script: ./gradlew connectedCheck


  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Assemble Release Bundle
        run:
          ./gradlew bundleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
            releaseDirectory: app/build/outputs/bundle/release
            signingKeyBase64: ${{ secrets.KEYSTORE }}
            alias: ${{ secrets.KEY_ALIAS }}
            keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
            keyPassword: ${{ secrets.EY_PASSWORD }}
